[WIP][Feature] add onboarding question from ATS hire
associatedemployers/granite pull request #762
Opened 2020-03-31 17:07 UTC by JavaLavaMT

closes #625 
close with associatedemployers/quartz#
close with associatedemployers/igneous#

![onboarding](https://user-images.githubusercontent.com/25805625/78054347-2b9c0300-733f-11ea-9c91-34fe34ac0bf7.gif)

2020-09-25 14:46 UTC, James1x0 approved these changes

2020-09-30 17:11 UTC, JavaLavaMT commented
close with associatedemployers/igneous#355

2020-09-30 17:43 UTC, James1x0 commented on app/controllers/account/job-opening/campaign/applicant-tracking.js
> +  confirmHireModalId=        'modal__ats-confirm-hire'
```suggestion
  confirmHireModalId =       'modal__ats-confirm-hire'
```

2020-09-30 17:44 UTC, James1x0 commented on app/models/employee.js
> +  OnboardingQuestionForm;
```suggestion
  onboardingQuestionForm;
```
That's a bug

2020-09-30 17:49 UTC, James1x0 requested changes
One last change. I think for the modal, you can increase the overall size by adding the `large` class to the modal.

2020-09-30 17:49 UTC, James1x0 commented on app/styles/granitestyles/components/modals/ats-hire.less
> +}
We need to do something else here. A static width will break mobile.

2020-09-30 17:49 UTC, James1x0 commented on app/components/modals/ats-hire.js
> +  employeeFields= [
```suggestion
  employeeFields = [
```

2020-09-30 17:51 UTC, James1x0 commented
@JavaLavaMT Once the width thing is fixed, please go to the review app: https://granite-prod-pr-762.herokuapp.com/

And just QA what you've added. I'm interested in making sure you check out the changes made to `form-element` and make sure those are a-ok.

2020-10-06 16:30 UTC, merged