Contribution management
associatedemployers/granite pull request #799
Opened 2020-08-31 19:45 UTC by JavaLavaMT

closes #780 
close with associatedemployers/igneous#340

<img width="1680" alt="Screen Shot 2020-08-31 at 1 21 42 PM" src="https://user-images.githubusercontent.com/25805625/91759188-793ac700-eb8e-11ea-853a-16000670cf42.png">
<img width="508" alt="Screen Shot 2020-08-31 at 1 21 55 PM" src="https://user-images.githubusercontent.com/25805625/91759197-7d66e480-eb8e-11ea-9046-4f7107171189.png">
<img width="1093" alt="Screen Shot 2020-08-31 at 1 22 02 PM" src="https://user-images.githubusercontent.com/25805625/91759198-7d66e480-eb8e-11ea-9825-0e49410654ef.png">
<img width="1677" alt="Screen Shot 2020-08-31 at 1 22 09 PM" src="https://user-images.githubusercontent.com/25805625/91759199-7dff7b00-eb8e-11ea-9475-4a26bb2fec0e.png">
<img width="304" alt="Screen Shot 2020-08-31 at 1 22 18 PM" src="https://user-images.githubusercontent.com/25805625/91759202-7dff7b00-eb8e-11ea-92f2-bdff5672bf92.png">
<img width="1614" alt="Screen Shot 2020-08-31 at 1 22 29 PM" src="https://user-images.githubusercontent.com/25805625/91759203-7e981180-eb8e-11ea-9011-fa15997fd9eb.png">
<img width="1272" alt="Screen Shot 2020-08-31 at 1 23 10 PM" src="https://user-images.githubusercontent.com/25805625/91759204-7e981180-eb8e-11ea-9c2f-2e24fbd5e1eb.png">

2020-09-01 13:39 UTC, James1x0 commented on app/components/benefits/contributions-row.hbs
> +          <label for="family-Wellness-Modifier">On Wellness Plan</label>
```suggestion
          <label for="family-Wellness-Modifier">On Wellness Plan</label>
```

Class names and ids should always be lower case

2020-09-01 13:40 UTC, James1x0 commented on app/components/benefits/contributions-table.js
> +  contributionGroups = [ 'Employee', 'Employee & Spouse', 'Employee & Children',' Family' ]
I think there's a rogue space in one of your strings here.

2020-09-01 13:41 UTC, James1x0 commented on app/components/benefits/contributions-table.js
> +    this.args.cancel();
I believe both cancel and save here can just be removed as intermediaries. In the template you can write:

{{fn @save  this.wp}}

2020-09-01 13:42 UTC, James1x0 commented on app/components/benefits/plan.hbs
> +          <u>{{format-money @plan.ratesEmployee}}{{if @plan.contributionsEmployeeWellnessModifier (concat " (" (format-money @plan.contributionsEmployeeWellnessModifier) "w/ wellness)") }}</u>
Unnecessary complication, don't use concat. You're in a template, just write it out in a block {{#if}}

2020-09-01 13:43 UTC, James1x0 commented on app/components/benefits/plan.hbs
> +  <div class="extra content plan-card__contributions">
BEM 💪 🤘

2020-09-01 13:44 UTC, James1x0 commented on app/components/benefits/plan.hbs
> +          {{#if (eq @plan.contributionsChildrenType 'dollar')}}
I'm sure that this is a template lint error :/
You should use double-quotes in templates.

2020-09-01 13:47 UTC, James1x0 commented on app/controllers/account/benefits/plans/contributions/edit-all.js
> +    });
While you are working on this, if we have a record array, like `model`, we can actually make use of Ember's ArrayProxy method called `invoke`

This becomes:
```
this.model.invoke('rollbackAttributes');
```

2020-09-01 13:48 UTC, James1x0 commented on app/components/benefits/contributions-table.hbs
> +    </Form::ActionButton>
I'm somewhat expecting you to make use of a "working" or "loading" state here. Too often, people will click a save button 3 times and cause errors.

2020-09-01 13:51 UTC, James1x0 commented on app/serializers/plan.js
> +
Sorta confused why you didn't use your existing methodology here: https://github.com/associatedemployers/granite/pull/799/files#diff-8c20260321c10644ee652fca0edfd7d5R27-R36

2020-09-01 13:54 UTC, James1x0 commented on app/templates/account/settings/index/features.hbs
> +      <label for="wellnessPlan">
![](https://media.giphy.com/media/fSB7KQML8Eixu4LnEl/giphy.gif)
```suggestion
      <label for="wellness-plan">
```

2020-09-01 13:55 UTC, James1x0 commented on app/templates/account/settings/index/features.hbs
> +        Does you company offer a wellness plan?, Enable this to change the contribution for wellness participants.
```suggestion
          Does your company offer a wellness plan? Enable this to change benefit contributions for wellness participants. 
```

2020-09-01 13:56 UTC, James1x0 commented on app/templates/account/settings/index/features.hbs
> +      <UiCheckbox @class="toggle" @label="On" @checked={{this.model.wellnessPlan}} @onChange={{pipe (set this.model.wellnessPlan _) (fn this.data.saveRecord this.model)}} />
![](https://media.giphy.com/media/vsvBFlxjvLoME/giphy.gif)

```suggestion
      <UiCheckbox @id="wellness-plan" @class="toggle" @label="On" @checked={{this.model.wellnessPlan}} @onChange={{pipe (set this.model.wellnessPlan _) (fn this.data.saveRecord this.model)}} />
```

2020-09-01 13:57 UTC, James1x0 commented on app/templates/account/benefits/plans/contributions/edit-all.hbs
> +<Benefits::ContributionsTable @plan={{this.model}} @contributions={{@contributionsGroups}} @cancel={{this.cancel}} @save={{this.save}} />
![](https://media.giphy.com/media/R0TrhAtNeUC0E/giphy.gif)

2020-09-01 13:57 UTC, James1x0 commented on app/templates/account/benefits/plans/contributions/edit.hbs
> +<Benefits::ContributionsTable @plan={{this.model}} @cancel={{this.cancel}} @save={{this.save}} />
![](https://media.giphy.com/media/3o7TKtsBMu4xzIV808/giphy.gif)

2020-09-01 15:37 UTC, JavaLavaMT commented on app/components/benefits/contributions-table.js
> +  contributionGroups = [ 'Employee', 'Employee & Spouse', 'Employee & Children',' Family' ]
👁 found it

2020-09-01 15:39 UTC, JavaLavaMT commented on app/components/benefits/contributions-table.js
> +    this.args.cancel();
I like that a lot better! good call

2020-09-01 16:12 UTC, JavaLavaMT commented on app/components/benefits/contributions-row.hbs
> +          <label for="family-Wellness-Modifier">On Wellness Plan</label>
🏁

2020-09-01 16:13 UTC, JavaLavaMT commented on app/components/benefits/plan.hbs
> +          {{#if (eq @plan.contributionsChildrenType 'dollar')}}
🏁

2020-09-01 16:22 UTC, JavaLavaMT commented on app/controllers/account/benefits/plans/contributions/edit-all.js
> +    });
learned something new

2020-09-01 16:53 UTC, JavaLavaMT commented on app/serializers/plan.js
> +
@James1x0 

I had problems with the dynamic "titles"
i.e. 
`json.contributions['$title']`

with the employee, it was a 
json['$title']

2020-09-01 17:06 UTC, JavaLavaMT commented on app/components/benefits/contributions-table.hbs
> +    </Form::ActionButton>
I totally was too, just completely forgot

2020-09-01 17:54 UTC, JavaLavaMT commented on app/components/benefits/plan.hbs
> +          <u>{{format-money @plan.ratesEmployee}}{{if @plan.contributionsEmployeeWellnessModifier (concat " (" (format-money @plan.contributionsEmployeeWellnessModifier) "w/ wellness)") }}</u>
🏁

2020-09-16 13:50 UTC, James1x0 commented on app/templates/account/employee/index/edit/job.hbs
> +    <UiCheckbox @class="checkbox" @label="Wellness Plan" @checked={{readonly this.model.wellnessPlan}} @onChange={{set this.model.wellnessPlan _}} />
```suggestion
    <UiCheckbox @class="checkbox" @label="Employee is on wellness plan" @checked={{readonly this.model.wellnessPlan}} @onChange={{set this.model.wellnessPlan _}} />
```

2020-09-16 13:51 UTC, James1x0 commented on app/templates/components/benefits/plan.hbs
> +            {{#if (and @plan.lifeCoverage (or (eq @plan.type "L") (eq @plan.type "DL")))}}
```suggestion
            {{#if (and @plan.lifeCoverage (eq @plan.type "L"))}}
```

2020-09-16 13:53 UTC, James1x0 commented on app/components/benefits/plan.hbs
> +              {{format-money @plan.contributionsEmployeeWellnessModifier}} w/ wellness
I really don't like how this is displayed. It seems to break the line flow. Let's do this, make this appear as:

$100.20/**$99.20**

with the second value having a tooltip titled, "With wellness modifier of -$1.00"

2020-09-16 13:54 UTC, James1x0 requested changes
There's a few things that still need adjustment

2020-09-16 13:54 UTC, James1x0 commented on app/components/benefits/contributions-row.hbs
> +      {{@plan.name}}
```suggestion
        {{@plan.name}}
```

2020-09-16 13:55 UTC, James1x0 commented on app/components/benefits/contributions-row.hbs
> +          <label for="family-Wellness-Modifier">On Wellness Plan</label>
```suggestion
          <label for="family-wellness-modifier">On Wellness Plan</label>
```
**Always** lowercase classes and ids.

2020-09-16 13:55 UTC, James1x0 commented on app/components/benefits/contributions-row.hbs
> +            <Input id="family-Wellness-Modifier" @type="number" @max={{0}} @value={{mut @plan.contributionsFamilyWellnessModifier}} />
```suggestion
            <Input id="family-wellness-modifier" @type="number" @max={{0}} @value={{mut @plan.contributionsFamilyWellnessModifier}} />
```
**Always** lowercase classes and ids.

2020-09-16 13:56 UTC, James1x0 commented on app/components/benefits/plan.hbs
> +            <div class="line-item-value">
Indentation here is really wonky

2020-09-16 13:56 UTC, James1x0 commented on app/components/benefits/plan.hbs
> +                <a href="" {{on "click" (prevent-default (toggle "showDescription" this))}}>{{if this.showDescription "Show Less" "Show More"}}</a>
```suggestion
                <a href="#" {{on "click" (prevent-default (toggle "showDescription" this))}}>{{if this.showDescription "Show Less" "Show More"}}</a>
```

2020-09-16 13:57 UTC, James1x0 commented on app/templates/account/benefits.hbs
> +            <LinkTo @route="account.benefits.plans.contributions.edit-all" class="item"><i class="edit icon"></i>Edit Contributions</LinkTo>s
```suggestion
            <LinkTo @route="account.benefits.plans.contributions.edit-all" class="item"><i class="edit icon"></i>Edit contributions</LinkTo>
```

2020-09-16 18:23 UTC, JavaLavaMT commented
![image](https://user-images.githubusercontent.com/25805625/93376796-61fb0b00-f817-11ea-90e6-e782727321ad.png)

![image](https://user-images.githubusercontent.com/25805625/93376819-69baaf80-f817-11ea-94eb-d444f3249bdc.png)

2020-09-16 18:24 UTC, JavaLavaMT commented
fixed $ 
![image](https://user-images.githubusercontent.com/25805625/93376942-9373d680-f817-11ea-9bea-6040a1598a9e.png)

2020-09-17 19:09 UTC, James1x0 approved these changes

2020-09-17 19:09 UTC, merged