[Bug] ATS screening responses should show a humanized date if a date is used
associatedemployers/granite pull request #839
Opened 2020-09-30 17:04 UTC by JavaLavaMT

closes #827

![image](https://user-images.githubusercontent.com/25805625/94716778-963cf400-030c-11eb-84c5-36a1d4843354.png)

2020-09-30 17:38 UTC, James1x0 requested changes

2020-09-30 17:38 UTC, James1x0 commented on app/controllers/account/job-opening/campaign/job-application/index.js
> +    return groups;
There's a more succinct way to do this. Expand on the existing map function, don't iterate on steps twice.

2020-09-30 17:38 UTC, James1x0 commented on app/templates/account/job-opening/campaign/job-application/index.hbs
> +              {{or group.response.value.text group.response.value}}
Rather than pre-formatting, I'd rather you use a flag and use the time helper. This bring display config into the display markup. 👍

2020-10-06 16:34 UTC, James1x0 commented on app/controllers/account/job-opening/campaign/job-application/index.js
> +    return groups;
```suggestion
    return steps && responses ? steps.toArray().map(step => {
      let response = responses.findBy('step', step.get('id'));
      return {
        step,
        response,
        date: typeof response.value === 'array' ? moment(response.value.text).isValid() : moment(response.value).isValid()
    })) : false;
```

2020-10-06 16:35 UTC, James1x0 commented on app/templates/account/job-opening/campaign/job-application/index.hbs
> +              {{or (time group.response.value) (time group.response.value.text)}}
```suggestion
              {{time (or group.response.value group.response.value.text)}}
```

2020-10-06 16:37 UTC, JavaLavaMT commented on app/controllers/account/job-opening/campaign/job-application/index.js
> +    return groups;
yep way better way, not sure what I was thinking

2020-10-08 19:08 UTC, James1x0 commented on app/controllers/account/job-opening/campaign/job-application/index.js
> +      date:     typeof this.response.value === 'array' ? moment(this.response.value.text).isValid() : moment(this.response.value).isValid()
```suggestion
      date:     moment(typeof this.response.value === 'array' ? this.response.value.text : this.response.value).isValid()
```

2020-10-08 19:09 UTC, merged